### ISSUE TITLE
关于http2

### ISSUE THREAD

**Issue by windy1lee** [1715173329/v2ray-onekey#1]
使用脚本可以配置成功h2-tls，能否加入客户端配置文件生成的功能！

**Comment by 1715173329** [comment]
客户端配置暂不支持，主要是懒得做
白话文教程里有教程，你可以自己参考下。

**Comment by 1715173329** [comment]
[Support for generating H2 VMESS link](https://github.com/1715173329/v2ray-onekey/commit/ac63b3bb6c9fcd12b04e5bdf05f863a9811a69b8)

现在已支持H2 VMESS链接生成。
